on:
  # Trigger the workflow on PR to the master branch
  pull_request:
    branches:
      - master

name: Check page rendering

jobs:
  render:
    name: Render Site
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown and distill
        run: |
          install.packages(c("rmarkdown", "distill", "dplyr", "tidyr", "jsonlite", "DT"), dependencies = TRUE)
        shell: Rscript {0}
      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
