on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

  # pull_request:
  #   branches:
  #     - master

name: Seb's Render Site Action

jobs:
  render:
    name: Render Site
    runs-on: macOS-latest
    # The action itself will push to master. Make sure we don't run in a
    # loop triggering this action by itself
    if: "!contains(github.event.head_commit.message, 'gh-action-seb')"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown and distill
        run: |
          install.packages(c("rmarkdown", "distill", "dplyr", "tidyr", "jsonlite", "DT"), dependencies = TRUE)
        shell: Rscript {0}
      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am 'gh-action-seb re-build site' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
